# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 14187ca1f011d0a9faebfcac86daa6dc5fc6b688e28e2fec8df496bf0bbeb736741084a59847718f2942294c2aba9392c26d728b6be301f4393599d8d74e1967

test:
  secret_key_base: 3832aac744232810b4ff6bd41f959dda86bd15b80b3009fa3151326a6290d344ff87c64bcec357dce4eb5961a888df26474d4852b008a76042ade818fa2d3cba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
