# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1a573251f40dc54f3fabc6ed94c84724143c32ab083a1ace3638087015bec56df0367d8f1d0c3fb8e3d1a46a46e32ce7ab9957c64a2a37b29326a910d4b9347c

test:
  secret_key_base: 6bf98f73e4e87a364cc50d5aea68405733298e9f7589e6b47fcd2e22b7da7b39ab7b874f6f6b9bdcf2997e05df85e9d0b05a98e23e10db79206fa739c6eee84d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
