# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 963389b3ab732a61c52ffeb93e5bc8ef37c781537923c3f225e3de901dcc2de26637be4f6708c0891ba4e626afd5d50b2c0be3e6f67b9983e7da0682d4ae9367

test:
  secret_key_base: a52b590099b870548959b8ecc99740abc9134c9dc9d96d55b5a1eaf894f6b8ba74ad8a700cb75c14dbcd48f4fce3e0ca759b4d51f7118673e10b452836cf7545

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
