# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 926f2a6e8ad18e3ae595d9912316cfc61101040a8ac2b41e3b34f5367195a8f6b45b5e42deadcb7e16d14c55c975d1c5833102f9e7dc674c58bd454e5182894d

test:
  secret_key_base: 069009db3387d54070ed740c5047447ffb0da537a8804f10b5e708c3fc6ce7113d396c72681b1551c03ab487bb8b15d7820233db7467e265f7abe2fea54ee85b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
