# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e7f6f7f4847b8ed2dc86366206f67b7107b2047658fde62f354f68b073ca81b042101ebfa5c115f6bc648149d2f9cac2f8f9c81a7523418b6954aa6bd0f4a4c4

test:
  secret_key_base: 0bc7853055518c2fa4e976fefdad5e01a48dac93210b4bf99bb1b68682e1065ba77e1b42c3122589f8363c5fea613ba37910d5515ab477f031ec5bfd90d70d3c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
